# Generated by Django 5.1 on 2026-09-30 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0006_conversation_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='Student',
            new_name='student',
        ),
    ]
