#defiine our expected output in a structured way 
from pydantic import BaseModel
from typing import List
#define expected structure of rag/ai response
class RAGResponse(BaseModel):
    #the actual answer generated by ai
    answer:str
    #list the sources to generate answer
    sources:List[str]
    #confidence level of answer
    confidence : str
